name: Release

on:
  push:
    branches:
      - master
      - alpha
      - beta
      - next

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Use Node.js v12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: npm ci
    
    - name: Run unit tests
      run: npm run test:ci
      env:
        CI: true

    - name: Build package and documentation
      run: npm run build
      env:
        CI: true

    - name: Build release
      run: npx semantic-release@17 --dry-run
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
